//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppleTimer.TimerServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimerServer.ITimerServer")]
    public interface ITimerServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimerServer/UserExists", ReplyAction="http://tempuri.org/ITimerServer/UserExistsResponse")]
        bool UserExists(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimerServer/UserExists", ReplyAction="http://tempuri.org/ITimerServer/UserExistsResponse")]
        System.Threading.Tasks.Task<bool> UserExistsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimerServer/GetUserByUsername", ReplyAction="http://tempuri.org/ITimerServer/GetUserByUsernameResponse")]
        DbModels.Models.User GetUserByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimerServer/GetUserByUsername", ReplyAction="http://tempuri.org/ITimerServer/GetUserByUsernameResponse")]
        System.Threading.Tasks.Task<DbModels.Models.User> GetUserByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimerServer/GetUserByGuid", ReplyAction="http://tempuri.org/ITimerServer/GetUserByGuidResponse")]
        DbModels.Models.User GetUserByGuid(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimerServer/GetUserByGuid", ReplyAction="http://tempuri.org/ITimerServer/GetUserByGuidResponse")]
        System.Threading.Tasks.Task<DbModels.Models.User> GetUserByGuidAsync(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimerServer/AddUser", ReplyAction="http://tempuri.org/ITimerServer/AddUserResponse")]
        void AddUser(DbModels.Models.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimerServer/AddUser", ReplyAction="http://tempuri.org/ITimerServer/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(DbModels.Models.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimerServerChannel : AppleTimer.TimerServer.ITimerServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimerServerClient : System.ServiceModel.ClientBase<AppleTimer.TimerServer.ITimerServer>, AppleTimer.TimerServer.ITimerServer {
        
        public TimerServerClient() {
        }
        
        public TimerServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimerServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimerServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimerServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UserExists(string username) {
            return base.Channel.UserExists(username);
        }
        
        public System.Threading.Tasks.Task<bool> UserExistsAsync(string username) {
            return base.Channel.UserExistsAsync(username);
        }
        
        public DbModels.Models.User GetUserByUsername(string username) {
            return base.Channel.GetUserByUsername(username);
        }
        
        public System.Threading.Tasks.Task<DbModels.Models.User> GetUserByUsernameAsync(string username) {
            return base.Channel.GetUserByUsernameAsync(username);
        }
        
        public DbModels.Models.User GetUserByGuid(System.Guid guid) {
            return base.Channel.GetUserByGuid(guid);
        }
        
        public System.Threading.Tasks.Task<DbModels.Models.User> GetUserByGuidAsync(System.Guid guid) {
            return base.Channel.GetUserByGuidAsync(guid);
        }
        
        public void AddUser(DbModels.Models.User user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(DbModels.Models.User user) {
            return base.Channel.AddUserAsync(user);
        }
    }
}
